-- Create accounts
create table
  public.accounts (
    id integer generated by default as identity,
    email text null,
    name text null,
    created_at timestamp with time zone not null default now(),
    constraint accounts_pkey primary key (id)
  ) tablespace pg_default;

-- Create customers 
create table
  public.customers (
    id integer generated by default as identity,
    account_id integer null,
    created_at timestamp with time zone not null default now(),
    constraint customers_pkey primary key (id),
    constraint customers_account_id_key unique (account_id),
    constraint customers_account_id_fkey foreign key (account_id) references accounts (id) on update cascade on delete restrict
  ) tablespace pg_default;


-- Create transactions
create table
  public.transactions (
    id integer generated by default as identity,
    description text null,
    created_at timestamp with time zone not null default now(),
    constraint transactions_pkey primary key (id)
  ) tablespace pg_default;

-- Create games
create table
  public.games (
    id integer generated by default as identity,
    item_sku text null,
    name text null,
    publisher text null,
    price_in_cents integer null,
    mode_review integer null,
    platform text null,
    genre text null,
    family_rating text null,
    release_date date null,
    created_at timestamp with time zone not null default now(),
    constraint games_pkey primary key (id),
    constraint games_item_sku_key unique (item_sku)
  ) tablespace pg_default;

-- Create carts
create table
  public.carts (
    id integer generated by default as identity,
    customer_id integer null,
    total_games integer null default 0,
    total_cost integer null default 0,
    created_at timestamp with time zone not null default now(),
    constraint carts_pkey primary key (id),
    constraint carts_customer_id_fkey foreign key (customer_id) references customers (id) on update cascade on delete restrict
  ) tablespace pg_default;

-- Create cart_items
create table
  public.cart_items (
    cart_id integer not null,
    game_id integer not null,
    cost integer null default 0,
    created_at timestamp with time zone not null default now(),
    constraint cart_items_pkey primary key (cart_id, game_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id) on update cascade on delete restrict,
    constraint cart_items_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete restrict
  ) tablespace pg_default;

-- Create purchases
create table
  public.purchases (
    account_id integer not null,
    game_id integer not null,
    transaction_id integer null,
    money_given integer null,
    play_time integer null default 0,
    created_at timestamp with time zone not null default now(),
    constraint purchases_pkey primary key (account_id, game_id),
    constraint purchases_account_id_fkey foreign key (account_id) references accounts (id) on update cascade on delete restrict,
    constraint purchases_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete restrict,
    constraint purchases_transaction_id_fkey foreign key (transaction_id) references transactions (id) on update cascade on delete restrict
  ) tablespace pg_default;

-- Create reviews
create table
  public.reviews (
    account_id integer not null,
    game_id integer not null,
    review integer null,
    created_at timestamp with time zone not null default now(),
    constraint reviews_pkey primary key (account_id, game_id),
    constraint reviews_account_id_fkey foreign key (account_id) references accounts (id) on update cascade on delete restrict,
    constraint reviews_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete restrict
  ) tablespace pg_default;

-- Create wishlisted
create table
  public.wishlisted (
    account_id integer not null,
    game_id integer not null,
    created_at timestamp with time zone not null default now(),
    constraint wishlisted_pkey primary key (account_id, game_id),
    constraint wishlisted_account_id_fkey foreign key (account_id) references accounts (id) on update cascade on delete restrict,
    constraint wishlisted_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete restrict
  ) tablespace pg_default;
